/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.popups;

import control.Cid10C;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import util.Yagami;

/**
 *
 * @author UNOPAR
 */
public class FindCid10 extends javax.swing.JDialog {

    public String idCid;

    /**
     * Creates new form Cid10
     */
    public FindCid10(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Cid10C.CONTROL.listTable(tableCid10, rootPaneCheckingEnabled, null, txtFiltro.getText());
        Yagami.resizeColumns2(tableCid10, 900, 3, 17);

    }

    // Variável para armazenar ID do Cid escolhido
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbFiltro1 = new javax.swing.JLabel();
        lbFiltro = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        spGrade = new javax.swing.JScrollPane();
        tableCid10 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lbFiltro1.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        lbFiltro1.setForeground(new java.awt.Color(153, 153, 153));
        lbFiltro1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFiltro1.setText("Pesquisa por Código ou Situação");

        lbFiltro.setText("Filtro:");

        txtFiltro.setColumns(30);
        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        tableCid10.setAutoCreateRowSorter(true);
        tableCid10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Cid10", "Descriçao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCid10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCid10MouseClicked(evt);
            }
        });
        spGrade.setViewportView(tableCid10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spGrade)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addComponent(lbFiltro1, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbFiltro1)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbFiltro)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(spGrade, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        TableRowSorter rs = (TableRowSorter) tableCid10.getRowSorter();
        rs.setRowFilter(RowFilter.regexFilter("(?i)" + txtFiltro.getText(), 0, 1));
    }//GEN-LAST:event_txtFiltroKeyReleased

    private void tableCid10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCid10MouseClicked

        if (evt.getClickCount() == 2) {
            //metodo para selecionar linha
            try {

                // Armazenar index da linha selecionada
                int linhaAtual = tableCid10.getSelectedRow();

                // Pegar valor do objeto da coluna 0 da linha selecionada to String
                idCid = String.valueOf(tableCid10.getValueAt(linhaAtual, 0));           
                

                // Fechar janela
                this.dispose();

            } catch (ArrayIndexOutOfBoundsException e) {
                // Alertar que deve selecionar uma linha caso não selecione.
                JOptionPane.showMessageDialog(
                        null,
                        "Você deve escolher um endereço.",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE
                );
            }

        }
    }//GEN-LAST:event_tableCid10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Look and Feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Cria e mostra Janela */
        java.awt.EventQueue.invokeLater(new FindCid10.RunnableImpl());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbFiltro;
    private javax.swing.JLabel lbFiltro1;
    private javax.swing.JScrollPane spGrade;
    private javax.swing.JTable tableCid10;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables

    private static class RunnableImpl implements Runnable {

        public RunnableImpl() {
        }

        @Override
        public void run() {
            CadEndereco dialog = new CadEndereco(new javax.swing.JFrame(), true);
            dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosing(java.awt.event.WindowEvent e) {
                    System.exit(0);
                }
            });
            dialog.setVisible(true);
        }
    }
}
